### ISSUE TITLE
Error when running deploy.py

### ISSUE THREAD

**Issue by byorgey** [marvinpinto/irc-hooky#22]
Hi there, thanks for this neat tool.  However, I haven't been able to get it to work, though I very well may be doing something wrong.  After following the instructions at https://disjoint.ca/projects/irc-hooky/deployment.html, I get the following error when running `deploy.py`:

```
$ deploy-env/bin/python deploy.py
INFO:irchooky:Policy arn:aws:iam::986877254258:policy/irc-hooky-lambda-basic-execution-role-policy successfully created.
INFO:irchooky:Role arn:aws:iam::986877254258:role/irc-hooky-lambda-basic-execution-role successfully created.
Traceback (most recent call last):
  File "deploy.py", line 354, in <module>
    dpl.create_lambda_function()
  File "deploy.py", line 152, in create_lambda_function
    Code={'ZipFile': encoded_zip}
  File "/home/brent/src/diagrams/irc-hooky/deploy-env/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/brent/src/diagrams/irc-hooky/deploy-env/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
```

Any ideas what could be causing this?

**Comment by byorgey** [comment]
[This stackoverflow answer](https://stackoverflow.com/a/37438525/305559) seems to suggest there can be some sort of race condition, and waiting 5-6 seconds after creating the role before trying to create the lambda function solves it.  And indeed, when I simply ran the deploy script again, now that the role already existed, it worked.  So perhaps it would make sense to add a little pause into the deploy script.
